// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IClaimModule$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IClaimModule";
  readonly sourceName: "contracts/IClaimModule.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"verify","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IClaimModule.sol";
  readonly buildInfoId: "solc-0_8_20-bce1268fd160a16e126051c527301dd54734530d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IClaimModule"]: IClaimModule$Type;
    ["contracts/IClaimModule.sol:IClaimModule"]: IClaimModule$Type;
  }
}